const WIDTH_SCREEN_DESKTOP = 1280;
const WIDTH_SCREEN_TABLET = 768;
const WIDTH_SCREEN_MOBILE = 480;

const QUANTITY_CARDS_DESKTOP = {total: 12, extra: 3};
const QUANTITY_CARDS_TABLET = {total: 8, extra: 2};
const QUANTITY_CARDS_MOBILE = {total: 5, extra: 2};

export  {
    WIDTH_SCREEN_DESKTOP,
    WIDTH_SCREEN_TABLET,
    WIDTH_SCREEN_MOBILE,
    QUANTITY_CARDS_DESKTOP,
    QUANTITY_CARDS_TABLET,
    QUANTITY_CARDS_MOBILE,
}
